spring.application.name=SpringMiniProject


spring.datasource.url=jdbc:postgresql://localhost:5432/habit_tracker_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2KB

server.port=9098


