spring.application.name=SpringMiniProject

spring.file-upload-path=src/main/resources/files


spring.datasource.url=jdbc:postgresql://localhost:5432/habit_tracker_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2KB

server.port=9098

rustfs.url=http://46.250.227.14:9078
rustfs.access.name=rustfsadmin
rustfs.access.secret=@rustfsadmin12351131@
rustfs.bucket.name=sr-mini-project-bucket
