spring.application.name=SpringMiniProject

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5555/postgres
spring.datasource.username=postgres
spring.datasource.password=password123

spring.datasource.driver-class-name=org.postgresql.Driver

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6060
spring.data.redis.password=
spring.cache.type=redis
spring.data.redis.timeout=60000

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yannvanneth.27@gmail.com
spring.mail.password=whht tjyv nryk tkvs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=8tUx1KmcDv7QiX47nAkCoJcY9+3MdiMI5N2s3sV8qS0=